<? php
echo '<html lang="en">';
echo '';
echo '<head>';
echo '';
echo '<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=UTF-8">';
echo '';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<meta name="description" content="">';
echo '<meta name="author" content="">';
echo '';
echo '<title>Wipro Product Management System</title>';
echo '';
echo '<!-- Bootstrap core CSS -->';
echo '<link href="bootstrap.min.css" rel="stylesheet" type="text/css">';
echo '';
echo '';
echo '<!-- Custom fonts for this template -->';
echo '<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">';
echo '<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">';
echo '<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>';
echo '<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>';
echo '<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>';
echo '';
echo '<!-- Custom styles for this template -->';
echo '<link href="agency.css" rel="stylesheet">';
echo '<link href="prod-cust.css" rel="stylesheet" type="text/css">';
echo '';
echo '<!-- Temporary navbar container fix -->';
echo '<style>';
echo '.navbar-toggler {';
echo 'z-index: 1;';
echo '}';
echo '';
echo '@media (max-width: 576px) {';
echo 'nav > .container {';
echo 'width: 100%;';
echo '}';
echo '}';
echo '';
echo '';
echo '</style>';
echo '';
echo '</head>';
echo '';
echo '<body id="page-top">';
echo '';
echo '<!-- Bootstrap core JavaScript -->';
echo '<script src="jquery.min.js"></script>';
echo '<script src="tether.min.js"></script>';
echo '<script src="bootstrap.min.js"></script>';
echo '';
echo '<!-- Plugin JavaScript -->';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>';
echo '<!-- Contact form JavaScript -->';
echo '<script src="jqBootstrapValidation.js"></script>';
echo '<script src="contact_me.js"></script>';
echo '';
echo '';
echo '<!-- Navigation -->';
echo '<nav class="navbar fixed-top navbar-toggleable-md navbar-inverse" id="mainNav">';
echo '<div class="container">';
echo '<img src="img/logos/Wipro_Logo_RGB.png" height="80px" width="110px"/>';
echo '';
echo '';
echo '<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">';
echo 'Menu <i class="fa fa-bars"></i>';
echo '</button>';
echo '';
echo '<a class="navbar-brand" href="#page-top">WIPRO TECHNOLOGIES</a>';
echo '<div class="collapse navbar-collapse" id="navbarResponsive">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#">Home</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#features">Features</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#portfolio">Menu</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#about">Process</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#team">Team</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#help">Help</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="#contact">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<!-- Header -->';
echo '<header class="masthead">';
echo '<div class="container">';
echo '<div class="intro-text">';
echo '<div class="intro-lead-in">Wipro Product Management System</div>';
echo '<div class="intro-heading"></div>';
echo '<a href="#features" class="btn btn-xl">Tell Me More</a>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '';
echo '<!-- Services -->';
echo '<section id="features">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Salient Features</h2>';
echo '<h3 class="section-subheading text-muted">Have a look at our salient features</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row text-center">';
echo '<div class="col-md-4">';
echo '<span class="fa-stack fa-4x">';
echo '<i class="fa fa-circle fa-stack-2x text-primary"></i>';
echo '<i class="fa fa-mobile fa-stack-1x fa-inverse"></i>';
echo '</span>';
echo '<h4 class="service-heading">Mobile Friendly</h4>';
echo '<p class="text-muted"> All of the design is mobile friendly and can we used with any type of device. Be it a desktop, laptop, tablet, or a mobile phone. Our service uses bootstrap technology to adapt to the screen size rendering the perfect UI every time.</p>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<span class="fa-stack fa-4x">';
echo '<i class="fa fa-circle fa-stack-2x text-primary"> </i>';
echo '<i class="fa fa-window-close fa-stack-1x fa-inverse"> </i>';
echo '</span>';
echo '<h4 class="service-heading">No Nitty Gritty</h4>';
echo '<p class="text-muted">It is a service that uses pure Salesforce+Heroku. Here we have utlised pure PHP, Salesforce, Heroku Postgres and Heroku Connect which run on the Heroku platform. No CMS like wordpress has been used here.</p>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<span class="fa-stack fa-4x">';
echo '<i class="fa fa-circle fa-stack-2x text-primary"></i>';
echo '<i class="fa fa-lock fa-stack-1x fa-inverse"></i>';
echo '</span>';
echo '<h4 class="service-heading">Security</h4>';
echo '<p class="text-muted">All data is kept secure in multiple databases in multiple servers. So, if anything happens with one server, you can always get the data from another server.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Menu -->';
echo '<section class="bg-faded" id="portfolio">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Menu</h2>';
echo '<h3 class="section-subheading text-muted">Manage your products...</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal1">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-plus fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/create.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>Create Product</h4>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal2">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-retweet fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/update.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>Update Product</h4>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal3">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-trash fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/delete.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>Delete Product</h4>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal4">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-search fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/search.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>Search Products</h4>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal5">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-th-list fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/all_prods.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>All Products</h4>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 portfolio-item">';
echo '<div class="portfolio-link" data-toggle="modal" href="#portfolioModal6">';
echo '<div class="portfolio-hover">';
echo '<div class="portfolio-hover-content">';
echo '<i class="fa fa-usd fa-5x"></i>';
echo '</div>';
echo '</div>';
echo '<img class="img-fluid" src="img/portfolio/catalog.png" alt="">';
echo '</div>';
echo '<div class="portfolio-caption">';
echo '<h4>Product Catalog</h4>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- About -->';
echo '<section id="about">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Process</h2>';
echo '<h3 class="section-subheading text-muted">How Product Management System can be utlized</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<ul class="timeline">';
echo '<li>';
echo '<div class="timeline-image">';
echo '<img class="rounded-circle img-fluid" src="img/about/create-products.jpg" alt="">';
echo '</div>';
echo '<div class="timeline-panel">';
echo '<div class="timeline-heading">';
echo '<h4>Step 1</h4>';
echo '<h4 class="subheading">Create Products</h4>';
echo '</div>';
echo '<div class="timeline-body">';
echo '<p class="text-muted">You can start by creating products and this way you have all your product offerings in your database.</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="timeline-inverted">';
echo '<div class="timeline-image">';
echo '<img class="rounded-circle img-fluid" src="img/about/update-products.jpg" alt="">';
echo '</div>';
echo '<div class="timeline-panel">';
echo '<div class="timeline-heading">';
echo '<h4>Step 2</h4>';
echo '<h4 class="subheading">Update Products</h4>';
echo '</div>';
echo '<div class="timeline-body">';
echo '<p class="text-muted">You can change or update your products if you need to because the products are already kept in the database.</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="timeline-image">';
echo '<img class="rounded-circle img-fluid" src="img/about/view-products.jpg" alt="">';
echo '</div>';
echo '<div class="timeline-panel">';
echo '<div class="timeline-heading">';
echo '<h4>Step 3</h4>';
echo '<h4 class="subheading">View Products</h4>';
echo '</div>';
echo '<div class="timeline-body">';
echo '<p class="text-muted">You will be able to view all your products in a simple table list view or you can see your whole product catalog</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="timeline-inverted">';
echo '<div class="timeline-image">';
echo '<img class="rounded-circle img-fluid" src="img/about/manage-products.jpg" alt="">';
echo '</div>';
echo '<div class="timeline-panel">';
echo '<div class="timeline-heading">';
echo '<h4>Step 4</h4>';
echo '<h4 class="subheading">Manage your products</h4>';
echo '</div>';
echo '<div class="timeline-body">';
echo '<p class="text-muted">Now you can track, manage, view, create, update delete or do anything with the database of products</p>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li class="timeline-inverted">';
echo '<div class="timeline-image">';
echo '<h4>Share your catalog with everyone!</h4>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Team -->';
echo '<section class="bg-faded" id="team">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Our Amazing Team</h2>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-sm-3">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/1.jpg" alt="">';
echo '<h4>Sunil Patwal</h4>';
echo '<p class="text-muted">Project Manager</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/sunil.patwal.54"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/2.jpg" alt="">';
echo '<h4>Nikhil Sharma</h4>';
echo '<p class="text-muted">Admin</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/dNikSTheGreat"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/3.jpg" alt="">';
echo '<h4>Dipojjal Chakrabarti</h4>';
echo '<p class="text-muted">SPOC</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/dipojjal"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-3">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/4.jpg" alt="">';
echo '<h4>Anu Goyal</h4>';
echo '<p class="text-muted">Developer</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/anu.goyal.359"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-4">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/5.jpg" alt="">';
echo '<h4>Pooja Bhimrav Kanse</h4>';
echo '<p class="text-muted">Developer</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/pooja.kanse2"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-4">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/6.jpg" alt="">';
echo '<h4>Aditya Kalra</h4>';
echo '<p class="text-muted">UI Designer</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/adikalra3"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-sm-4">';
echo '<div class="team-member">';
echo '<img class="mx-auto rounded-circle" src="img/team/7.jpg" alt="">';
echo '<h4>Surabhi Rastogi</h4>';
echo '<p class="text-muted">UI Designer</p>';
echo '<ul class="list-inline social-buttons">';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="https://www.facebook.com/surabhi.rastogi1"><i class="fa fa-facebook"></i></a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="#"><i class="fa fa-linkedin"></i></a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Help & Support -->';
echo '<section id="help">';
echo '';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Help & Support</h2>';
echo '<h3 class="section-subheading text-muted">Let us know what you're interested in...</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '';
echo '<form action="https://webto.salesforce.com/servlet/servlet.WebToCase?encoding=UTF-8" method="POST">';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '';
echo '<div class="form-group">';
echo '<input  id="first_name" class="form-control" maxlength="40" name="first_name" size="20" type="text" placeholder="Your First Name *" required data-validation-required-message="Please enter your first name." />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<input type=hidden name="orgid" value="00D6A000000sm1O">';
echo '<input type=hidden name="retURL" value="http://www.prod-mgmt.com/case_thankyou.php">';
echo '';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '';
echo '<div class="form-group">';
echo '<input id="last_name" class="form-control" maxlength="40" name="last_name" size="20" type="text" placeholder="Your Last Name *" required data-validation-required-message="Please enter your first name."/>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '';
echo '<div class="form-group">';
echo '<input id="email" class="form-control" maxlength="40" name="email" size="20" type="text" placeholder="Email" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<div class="form-group">';
echo '<input id="phone" class="form-control" maxlength="40" name="phone" size="20" type="text" placeholder="Phone" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<div class="form-group">';
echo '<input id="subject" class="form-control" maxlength="40" name="subject" size="20" type="text" placeholder="Subject" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<div class="form-group">';
echo '<textarea name="description" class="form-control" placeholder="Description"></textarea>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<input type="hidden" id="external" name="external" value="1" />';
echo '';
echo '<button type="submit" name="submit" class="btn btn-xl">Submit Query</button>';
echo '';
echo '</form>';
echo '';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Contact -->';
echo '';
echo '<section id="contact">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12 text-center">';
echo '<h2 class="section-heading">Contact Us</h2>';
echo '<h3 class="section-subheading text-muted">Let us know what you're interested in...</h3>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '';
echo '<form id="contactForm" name="sentMessage" action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST" novalidate>';
echo '';
echo '<input type=hidden name="oid" value="00D6A000000sm1O">';
echo '<input type=hidden name="retURL" value="http://prod-mgmt.com/thankyou.php">';
echo '<div class="row">';
echo '<div class="col-md-6">';
echo '<div class="form-group">';
echo '<input  id="first_name" class="form-control" maxlength="40" name="first_name" size="20" type="text" placeholder="Your First Name *" required data-validation-required-message="Please enter your first name." />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input  id="last_name" class="form-control" maxlength="80" name="last_name" size="20" type="text" placeholder="Your Last Name *" required data-validation-required-message="Please enter your last name." />';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input id="email" class="form-control" maxlength="80" name="email" size="20" type="email" placeholder="Your Email *" required data-validation-required-message="Please enter your email address." />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input id="company" class="form-control" maxlength="40" name="company" size="20" type="text" placeholder="Your Company Name" />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input id="mobile" class="form-control" maxlength="40" name="mobile" size="20" type="text" placeholder="Your mobile *" required data-validation-required-message="Please enter your phone number." />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="col-md-6">';
echo '';
echo '';
echo '';
echo '<div class="form-group">';
echo '';
echo '<select  id="industry" class="form-control" name="industry">';
echo '<option value="">--Select Industry--</option>';
echo '<option value="Agriculture">Agriculture</option>';
echo '<option value="Apparel">Apparel</option>';
echo '<option value="Banking">Banking</option>';
echo '<option value="Biotechnology">Biotechnology</option>';
echo '<option value="Chemicals">Chemicals</option>';
echo '<option value="Communications">Communications</option>';
echo '<option value="Construction">Construction</option>';
echo '<option value="Consulting">Consulting</option>';
echo '<option value="Education">Education</option>';
echo '<option value="Electronics">Electronics</option>';
echo '<option value="Energy">Energy</option>';
echo '<option value="Engineering">Engineering</option>';
echo '<option value="Entertainment">Entertainment</option>';
echo '<option value="Environmental">Environmental</option>';
echo '<option value="Finance">Finance</option>';
echo '<option value="Food &amp; Beverage">Food &amp; Beverage</option>';
echo '<option value="Government">Government</option>';
echo '<option value="Healthcare">Healthcare</option>';
echo '<option value="Hospitality">Hospitality</option>';
echo '<option value="Insurance">Insurance</option>';
echo '<option value="Machinery">Machinery</option>';
echo '<option value="Manufacturing">Manufacturing</option>';
echo '<option value="Media">Media</option>';
echo '<option value="Not For Profit">Not For Profit</option>';
echo '<option value="Recreation">Recreation</option>';
echo '<option value="Retail">Retail</option>';
echo '<option value="Shipping">Shipping</option>';
echo '<option value="Technology">Technology</option>';
echo '<option value="Telecommunications">Telecommunications</option>';
echo '<option value="Transportation">Transportation</option>';
echo '<option value="Utilities">Utilities</option>';
echo '<option value="Other">Other</option>';
echo '</select>';
echo '';
echo '';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<input id="employees" class="form-control" name="employees" size="20" type="text" value="" placeholder="Number of employees in your company" />';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '<div class="form-group">';
echo '<textarea name="description" class="form-control" placeholder="Your query"></textarea>';
echo '<p class="help-block text-danger"></p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="clearfix"></div>';
echo '';
echo '<div class="col-lg-12 text-center">';
echo '<div id="success"></div>';
echo '<button class="btn btn-xl" type="submit">Send Message</button>';
echo '</div>';
echo '';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<!-- Footer -->';
echo '<footer>';
echo '<div class="container">';
echo '<span class="copyright">Copyright &copy; Wipro Product Management System 2017</span>';
echo '</div>';
echo '</footer>';
echo '';
echo '<!-- Portfolio Modals -->';
echo '';
echo '<!-- Modal 1 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '';
echo '<form>';
echo '<fieldset class="textt">';
echo '<legend><h2>Create Product</h2></legend>';
echo '<b>Product Name</b> <input type="text" name="name" placeholder="Enter Product Name"></br>';
echo '';
echo '<b style="opacity: 1;">Product Code</b>  <input type="text" name="id" placeholder="Enter Product Name"></br>';
echo '<p><b>';
echo 'Product Family</b>';
echo '<select name="family">';
echo '<option value="">Select</option>';
echo '<option value="m">Medicare</option>';
echo '<option value="c">Commercial</option>';
echo '<option value="a">Aspire</option>';
echo '<option value="e">Education</option>';
echo '</select>';
echo '</p>';
echo '';
echo '<b>isActive</b>  <input type="checkbox" name="isActive"></br>';
echo '</br>';
echo '<b>Description</b>  </br><br/>';
echo '<textarea name="comment" rows="5" cols="40"></textarea>';
echo '</br></br>';
echo '<input type="submit" value="Save"></t>';
echo '<input type="reset" value="Reset">';
echo '';
echo '</fieldset>';
echo '';
echo '</form>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Modal 2 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '';
echo '<form>';
echo '<fieldset>';
echo '<legend><h2>Update Product</h2></legend>';
echo '<div>';
echo '<b>Product Code</b>';
echo '';
echo '<input type="text" id="s" name="search" placeholder="Search.." align=right>';
echo '<button class="button"><span>Update</span></button>';
echo '';
echo '</fieldset>';
echo '';
echo '</form>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Modal 3 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '';
echo '<form>';
echo '<fieldset>';
echo '<legend><h2>Delete Product</h2></legend>';
echo '<div>';
echo '<b>Product ID</b>';
echo '';
echo '<input type="text" id="s" name="search" placeholder="Search..">';
echo '';
echo '<button class="button"><span>Delete</span></button>';
echo '</fieldset>';
echo '';
echo '</form>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Modal 4 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '';
echo '<form name="search-prod">';
echo '';
echo '';
echo '';
echo '<fieldset>';
echo '';
echo '<legend><h2>Search Product</h2></legend>';
echo '';
echo '<div>';
echo '';
echo '<b>Product ID</b>';
echo '';
echo '';
echo '';
echo '<input type="text" name="search" placeholder="Search..."/>';
echo '';
echo '';
echo '';
echo '<button class="button" type="submit"><span><b>Search</b></span></button>';
echo '';
echo '</fieldset>';
echo '';
echo '';
echo '';
echo '</form>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Modal 5 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '';
echo '<div class=\"panel-heading\"><center><h2>All Products</h2></center></div>';
echo '';
echo '';
echo '';
echo '<div class=\"panel-body\">';
echo '';
echo '<div class=\"container\">';
echo '';
echo '<table class=\"table table-striped\" cellspacing="10">';
echo '';
echo '<tr>';
echo '';
echo '<th>ID</th>';
echo '';
echo '<th>SALESFORCE ID</th>';
echo '';
echo '<th>NAME</th>';
echo '';
echo '<th>ACTIVE</th>';
echo '';
echo '<th>PRODUCT CODE</th>';
echo '';
echo '<th>DESCRIPTION</th>';
echo '';
echo '<th>COUNTRY</th>';
echo '';
echo '<th>STATE</th>';
echo '';
echo '</tr>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<td>0</td>';
echo '<td>1</td>';
echo '<td>2</td>';
echo '<td>3</td>';
echo '<td>4</td>';
echo '<td>5</td>';
echo '<td>6</td>';
echo '<td>7</td> </tr>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</table>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Modal 6 -->';
echo '<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">';
echo '<div class="modal-dialog">';
echo '<div class="modal-content">';
echo '<div class="close-modal" data-dismiss="modal">';
echo '<div class="lr">';
echo '<div class="rl">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 offset-lg-2">';
echo '<div class="modal-body">';
echo '<!-- Project Details Go Here -->';
echo '<h2>Product Catalog</h2>';
echo '';
echo 'Product catalog using lightning out... Coming soon!';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Custom scripts for this template -->';
echo '<script src="agency.min.js"></script>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>
